spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/myhome?useSSL=true
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
mybatis:
    mapper-locations: classpath:mapper/*.xml
config:
    file:
        prefix : F:/test/